using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Text.Json;
using System.Text.RegularExpressions;
using YoutubeExplode.Videos.ClosedCaptions;

internal sealed record Subtitle(string Language, string Name, bool Automatic, string Url)
{
    public static readonly string[] Formats =
    [
        "json3",
        "srv1",
        "srv2",
        "srv3",
        "ttml",
        "srt",
        "vtt",
    ];

    public string FormatUrl(string format) => Query(Url, "fmt", format);

    public static string Query(string url, string key, string value)
    {
        var uri = new UriBuilder(url);
        var parts = uri
            .Query.TrimStart('?')
            .Split('&', StringSplitOptions.RemoveEmptyEntries)
            .Where(x =>
                x.Split('=', 2)[0] is not "xosf" and not "format" && x.Split('=', 2)[0] != key
            );
        uri.Query = string.Join(
            '&',
            parts.Append(Uri.EscapeDataString(key) + "=" + Uri.EscapeDataString(value))
        );
        return uri.Uri.AbsoluteUri;
    }
}

internal sealed class CaptionInfo(
    string id,
    string originalUrl,
    JsonElement player,
    ClosedCaptionManifest manifest,
    Options options
)
{
    private JsonElement Details =>
        player.TryGetProperty("videoDetails", out var value) ? value : default;

    private string? Detail(string name) =>
        Details.ValueKind == JsonValueKind.Object && Details.TryGetProperty(name, out var value)
            ? value.ToString()
            : null;

    public string Title => Detail("title") ?? id;
    public Dictionary<string, Subtitle> Manual { get; } = new(StringComparer.Ordinal);
    public Dictionary<string, Subtitle> Automatic { get; } = new(StringComparer.Ordinal);
    public Dictionary<string, (Subtitle Subtitle, string Format, string? File)> Selected { get; } =
        new(StringComparer.Ordinal);

    public void Populate()
    {
        foreach (var track in manifest.Tracks)
        {
            var sub = new Subtitle(
                track.Language.Code,
                track.Language.Name,
                track.IsAutoGenerated,
                track.Url
            );
            if (!sub.Automatic)
                Manual.TryAdd(sub.Language, sub);
            else
            {
                Automatic.TryAdd(
                    sub.Language + "-orig",
                    sub with
                    {
                        Language = sub.Language + "-orig",
                        Name = sub.Name + " (Original)",
                    }
                );
                Automatic.TryAdd(sub.Language, sub);
            }
        }
        if (
            (options.WriteAutoSubs || options.ListSubs)
            && options.ExtractorArguments.GetValueOrDefault("skip") != "translated_subs"
            && player.TryGetProperty("captions", out var captions)
            && captions.TryGetProperty("playerCaptionsTracklistRenderer", out var renderer)
            && renderer.TryGetProperty("translationLanguages", out var languages)
        )
        {
            foreach (var track in manifest.Tracks)
            foreach (var language in languages.EnumerateArray())
            {
                var code = language.GetProperty("languageCode").GetString()!;
                if (code == track.Language.Code)
                    continue;
                var key = track.IsAutoGenerated ? code : code + "-" + track.Language.Code;
                var name =
                    language.TryGetProperty("languageName", out var n)
                    && n.TryGetProperty("simpleText", out var text)
                        ? text.GetString()!
                        : code;
                Automatic.TryAdd(
                    key,
                    new Subtitle(key, name, true, Subtitle.Query(track.Url, "tlang", code))
                );
            }
        }
    }

    public void Select(Action<string> warning)
    {
        var available = new Dictionary<string, Subtitle>(StringComparer.Ordinal);
        if (options.WriteSubs)
            foreach (var pair in Manual)
                available[pair.Key] = pair.Value;
        if (options.WriteAutoSubs)
            foreach (var pair in Automatic)
                available.TryAdd(pair.Key, pair.Value);
        if (available.Count == 0)
            return;
        var requested = new List<string>();
        if (options.SubLanguages.Count == 0)
        {
            var manual = available
                .Values.Where(x => !x.Automatic)
                .Select(x => x.Language)
                .ToArray();
            var all = available.Keys;
            requested.Add(
                manual.FirstOrDefault(x => x == "en")
                    ?? manual.FirstOrDefault(x => x.StartsWith("en", StringComparison.Ordinal))
                    ?? all.FirstOrDefault(x => x == "en")
                    ?? all.FirstOrDefault(x => x.StartsWith("en", StringComparison.Ordinal))
                    ?? manual.FirstOrDefault()
                    ?? all.First()
            );
        }
        else
        {
            foreach (var pattern in options.SubLanguages)
            {
                var exclude = pattern.StartsWith('-');
                var expression = exclude ? pattern[1..] : pattern;
                var matches =
                    expression == "all"
                        ? available.Keys.ToArray()
                        : available
                            .Keys.Where(x =>
                                Regex.IsMatch(
                                    x,
                                    "\\A(?:" + expression + ")\\z",
                                    RegexOptions.None,
                                    TimeSpan.FromSeconds(1)
                                )
                            )
                            .ToArray();
                if (exclude)
                    requested.RemoveAll(x => matches.Contains(x));
                else
                    foreach (var language in matches)
                        if (!requested.Contains(language))
                            requested.Add(language);
            }
        }
        foreach (var language in requested)
        {
            var format = options
                .SubFormat.Split('/')
                .FirstOrDefault(x => x == "best" || Subtitle.Formats.Contains(x));
            if (format is null)
            {
                warning($"No subtitle format matched '{options.SubFormat}'; using vtt.");
                format = "vtt";
            }
            if (format == "best")
                format = "vtt";
            Selected[language] = (available[language], format, null);
        }
    }

    public string Filename(string language, string format)
    {
        var template = options.Templates.GetValueOrDefault(
            "subtitle",
            options.Templates["default"]
        );
        if (template.Length == 0)
            return "";
        var name = Regex.Replace(
            template,
            @"%%|%\(([^)]+)\)([0-9]*[sd])",
            m =>
            {
                if (m.Value == "%%")
                    return "%";
                var value = m.Groups[1].Value switch
                {
                    "id" => id,
                    "title" => Title,
                    "ext" => format,
                    "uploader" or "channel" => Detail("author") ?? "NA",
                    "channel_id" => Detail("channelId") ?? "NA",
                    "duration" => Detail("lengthSeconds") ?? "NA",
                    _ => throw new ArgumentException(
                        $"Output template field is not implemented: {m.Groups[1].Value}"
                    ),
                };
                if (m.Groups[2].Value.EndsWith('d') && m.Groups[2].Value.Length > 1)
                    value = value.PadLeft(
                        int.Parse(m.Groups[2].Value[..^1], CultureInfo.InvariantCulture),
                        '0'
                    );
                return Sanitize(value);
            }
        );
        if (name.Contains("%(", StringComparison.Ordinal))
            throw new ArgumentException("Unsupported output template expression.");
        var suffix = "." + format;
        name =
            (name.EndsWith(suffix, StringComparison.Ordinal) ? name[..^suffix.Length] : name)
            + "."
            + Sanitize(language)
            + suffix;
        var home = Configuration.Expand(options.Paths.GetValueOrDefault("home", "."));
        var path = Configuration.Expand(options.Paths.GetValueOrDefault("subtitle", ""));
        return Path.GetFullPath(Path.Combine(home, path, name));
    }

    private static string Sanitize(string value) =>
        Regex.Replace(value.Replace('/', '⧸').Replace('\\', '⧹'), @"[\x00-\x1f<>:""|?*]", "_");

    public void WriteJson(Stream stream)
    {
        using var json = new Utf8JsonWriter(stream);
        json.WriteStartObject();
        json.WriteString("id", id);
        json.WriteString("title", Title);
        json.WriteString("webpage_url", "https://www.youtube.com/watch?v=" + id);
        json.WriteString("original_url", originalUrl);
        json.WriteString("extractor", "youtube");
        json.WriteString("extractor_key", "Youtube");
        json.WriteString("description", Detail("shortDescription"));
        json.WriteString("uploader", Detail("author"));
        json.WriteString("channel", Detail("author"));
        json.WriteString("channel_id", Detail("channelId"));
        if (long.TryParse(Detail("lengthSeconds"), out var duration))
            json.WriteNumber("duration", duration);
        if (long.TryParse(Detail("viewCount"), out var views))
            json.WriteNumber("view_count", views);
        json.WriteString(
            "language",
            manifest.Tracks.FirstOrDefault(x => x.IsAutoGenerated)?.Language.Code
        );
        WriteMap(json, "subtitles", Manual);
        WriteMap(json, "automatic_captions", Automatic);
        if (Selected.Count == 0)
            json.WriteNull("requested_subtitles");
        else
        {
            json.WriteStartObject("requested_subtitles");
            foreach (var pair in Selected)
            {
                json.WritePropertyName(pair.Key);
                WriteFormat(json, pair.Value.Subtitle, pair.Value.Format, pair.Value.File);
            }
            json.WriteEndObject();
        }
        json.WriteEndObject();
        json.Flush();
        stream.WriteByte((byte)'\n');
    }

    private static void WriteMap(Utf8JsonWriter json, string name, Dictionary<string, Subtitle> map)
    {
        json.WriteStartObject(name);
        foreach (var pair in map)
        {
            json.WriteStartArray(pair.Key);
            foreach (var format in Subtitle.Formats)
                WriteFormat(json, pair.Value, format, null);
            json.WriteEndArray();
        }
        json.WriteEndObject();
    }

    private static void WriteFormat(Utf8JsonWriter json, Subtitle sub, string format, string? path)
    {
        json.WriteStartObject();
        json.WriteString("ext", format);
        json.WriteString("url", sub.FormatUrl(format));
        json.WriteString("name", sub.Name);
        if (path is not null)
            json.WriteString("filepath", path);
        json.WriteEndObject();
    }
}
